apiVersion: apps/v1
kind: Deployment
metadata:
  name: compilot-frontend
  namespace: default
  labels:
    app: compilot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compilot-frontend
  template:
    metadata:
      labels:
        app: compilot-frontend
    spec:
      containers:
        - name: frontend
          image: ahusseini07/compilot-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: compilot-frontend
  namespace: default
spec:
  selector:
    app: compilot-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
